"""Tests for the WikiBackend Protocol and LocalFileBackend.

These tests verify the storage primitives in isolation. The Wiki
class is not exercised here — the next commit wires Wiki to the
backend.
"""

from __future__ import annotations

import json
import shutil
import sys
import tempfile
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from llmwikify.kernel.storage.backend import LocalFileBackend, WikiBackend


@pytest.fixture
def backend_root():
    temp = Path(tempfile.mkdtemp())
    yield temp
    shutil.rmtree(temp, ignore_errors=True)


@pytest.fixture
def backend(backend_root):
    (backend_root / "raw").mkdir()
    (backend_root / "wiki").mkdir()
    return LocalFileBackend(backend_root)


def test_local_backend_init(backend, backend_root):
    """Paths are configured correctly from config defaults."""
    assert backend.root == backend_root.resolve()
    assert backend.wiki_dir == (backend_root / "wiki").resolve()
    assert backend.raw_dir == (backend_root / "raw").resolve()
    assert backend.db_path == (backend_root / ".llmwikify.db").resolve()
    assert backend.index is not None
    assert backend.index.db_path == backend.db_path


def test_local_backend_get_put_page(backend):
    """Round-trip a page through get_page / put_page."""
    assert backend.get_page("hello") is None
    backend.put_page("hello", "world")
    assert backend.get_page("hello") == "world"


def test_local_backend_get_put_page_in_subdir(backend):
    """put_page creates parent directories automatically."""
    backend.put_page("concepts/Factor Investing", "factor body")
    assert backend.get_page("concepts/Factor Investing") == "factor body"
    assert (backend.wiki_dir / "concepts" / "Factor Investing.md").exists()


def test_local_backend_delete_page(backend):
    """delete_page removes the file and returns True; missing file returns False."""
    backend.put_page("temp", "x")
    assert backend.delete_page("temp") is True
    assert backend.get_page("temp") is None
    assert backend.delete_page("temp") is False


def test_local_backend_list_page_paths(backend):
    """list_page_paths returns all *.md files under wiki_dir, sorted."""
    backend.put_page("a", "1")
    backend.put_page("b", "2")
    backend.put_page("concepts/c", "3")
    paths = backend.list_page_paths()
    assert len(paths) == 3
    assert paths[0].name == "a.md"
    assert paths[1].name == "b.md"
    assert paths[2].name == "c.md"
    assert all(p.suffix == ".md" for p in paths)


def test_local_backend_get_put_index(backend):
    """get_index returns '' for missing; put_index writes the file."""
    assert backend.get_index() == ""
    backend.put_index("# Index\n- [[hello]]\n")
    assert backend.get_index() == "# Index\n- [[hello]]\n"


def test_local_backend_get_put_wiki_md(backend):
    """wiki.md is stored at root level (not in wiki/)."""
    assert backend.get_wiki_md() is None
    backend.put_wiki_md("# Wiki Schema\n\n## Page Types\n")
    assert backend.get_wiki_md() == "# Wiki Schema\n\n## Page Types\n"
    assert (backend.root / "wiki.md").exists()


def test_local_backend_merge_wiki_md_no_changes(backend):
    """merge returns existing unchanged (with version bump) when no new sections."""
    existing = "# Wiki\n\nGenerated by llmwikify v0.10.0\n\n## Page Types\n\n| Source | wiki/sources/ | ...\n"
    new = "# Wiki\n\n## Page Types\n\n| Source | wiki/sources/ | ...\n"
    merged = backend.merge_wiki_md(existing, new)
    assert "## Schema Updates" not in merged
    import re as _re
    assert _re.search(r"Generated by llmwikify v[\d.]+", merged)


def test_local_backend_merge_wiki_md_adds_sections(backend):
    """merge appends new H2 sections wrapped in Schema Updates block."""
    existing = "# Wiki\n\n## Page Types\n\nold content\n"
    new = "# Wiki\n\n## Page Types\n\n| Source | wiki/sources/ | ...\n\n## Best Practices\n\nnew content\n"
    merged = backend.merge_wiki_md(existing, new)
    assert "## Schema Updates" in merged
    assert "Best Practices" in merged
    assert "WIKI SCHEMA UPDATE NOTICE" in merged


def test_local_backend_append_log(backend):
    """append_log writes a timestamped entry to log.md."""
    entry = {"timestamp": "2026-06-06T12:00:00Z", "operation": "init", "details": "Wiki created"}
    result = backend.append_log(entry)
    log_path = backend.wiki_dir / "log.md"
    assert log_path.exists()
    log_content = log_path.read_text()
    assert "2026-06-06T12:00:00Z" in log_content
    assert "init" in log_content
    assert "Wiki created" in log_content
    assert result["operation"] == "init"


def test_local_backend_append_log_default_timestamp(backend):
    """If timestamp missing, backend generates one."""
    entry = {"operation": "test", "details": "no ts"}
    result = backend.append_log(entry)
    assert "timestamp" in result
    assert result["operation"] == "test"


def test_local_backend_source_cache_roundtrip(backend):
    """put_source_cache writes an HTML comment; get_source_cache parses it back."""
    backend.put_page("sources/article", "# Article\n\nbody")
    backend.put_source_cache("sources/article", "abc123", {"topics": ["x", "y"], "entities": []})
    cached = backend.get_source_cache("sources/article")
    assert cached is not None
    assert cached["hash"] == "abc123"
    assert cached["data"]["topics"] == ["x", "y"]


def test_local_backend_source_cache_updates_existing(backend):
    """put_source_cache replaces existing analysis comment (not appends duplicate)."""
    backend.put_page("sources/article", "# Article\n")
    backend.put_source_cache("sources/article", "v1", {"x": 1})
    backend.put_source_cache("sources/article", "v2", {"x": 2})
    cached = backend.get_source_cache("sources/article")
    assert cached["hash"] == "v2"
    assert cached["data"]["x"] == 2
    content = backend.get_page("sources/article")
    assert content.count("<!-- llmwikify:analysis") == 1


def test_local_backend_source_cache_missing_page(backend):
    """get_source_cache returns None for missing page; put is a no-op."""
    assert backend.get_source_cache("missing") is None
    backend.put_source_cache("missing", "h", {"a": 1})


def test_local_backend_get_page_type_mapping(backend):
    """Parse a wiki.md Page Types table into a dict."""
    wiki_md = (
        "# Wiki\n\n"
        "## Page Types\n\n"
        "| Type | Location | Purpose |\n"
        "|------|----------|---------|\n"
        "| Source | wiki/sources/{slug}.md | ingested source |\n"
        "| Concept | wiki/concepts/{name}.md | concept summary |\n"
        "\n## Workflow\n\nstuff\n"
    )
    backend.put_wiki_md(wiki_md)
    mapping = backend.get_page_type_mapping()
    assert mapping == {"Source": "sources", "Concept": "concepts"}


def test_local_backend_get_page_type_mapping_missing(backend):
    """Empty mapping when wiki.md doesn't exist."""
    assert backend.get_page_type_mapping() == {}


def test_local_backend_unicode_filenames(backend):
    """put_page handles unicode in page names."""
    backend.put_page("概念/风险平价", "中文内容")
    assert backend.get_page("概念/风险平价") == "中文内容"


def test_local_backend_get_page_missing_returns_none(backend):
    """get_page returns None for missing pages (not an exception)."""
    assert backend.get_page("nonexistent") is None


def test_local_backend_index_path_traversal_safe(backend):
    """Page names with '..' are not allowed in put_page (defense in depth)."""
    with pytest.raises((ValueError, OSError)):
        backend.put_page("../../etc/passwd", "x")


def test_wiki_backend_protocol_is_protocol():
    """WikiBackend is a typing.Protocol — LocalFileBackend satisfies it structurally."""
    from typing import runtime_checkable

    assert hasattr(WikiBackend, "get_page")
    assert hasattr(WikiBackend, "put_page")
    assert hasattr(WikiBackend, "merge_wiki_md")
    assert hasattr(WikiBackend, "append_log")
    assert hasattr(LocalFileBackend, "get_page")
    assert hasattr(LocalFileBackend, "merge_wiki_md")
