"""OS keyring wrapper for the JWT signing secret.

Layer: L1 (foundation). Hard-fails on missing backend (decision: keyring
fallback = hard fail, see auth-and-sharing-roadmap.md §0).

Storage location:
    service: llmwikify
    user:    jwt_secret
    value:   32 random bytes (generated by `set_secret` on first call)

If the user has no OS keyring daemon (e.g. headless Linux without
gnome-keyring-daemon or kwallet), `keyring` raises NoKeyringError.
We convert that to a clear AuthError instructing the user to install a
backend. We do NOT silently fall back to a file — that's an explicit
out-of-scope decision (decision: no file fallback).

Why hard-fail: silently writing a secret to `~/.llmwikify/auth_secret`
with mode 0o600 looks safe, but a backup tarball, a Docker image layer,
or a CI log can leak it. The user must opt in to a real keystore.
"""

from __future__ import annotations

import secrets
from functools import lru_cache

import keyring
import keyring.errors

from ._errors import AuthError

# Constants for the keyring slot. Service name is namespaced under the
# package; user is fixed. The 32-byte secret is hex-encoded for storage
# (keyring backends commonly expect str; hex is round-trip safe).
KEYRING_SERVICE = "llmwikify"
KEYRING_USER = "jwt_secret"
SECRET_BYTES = 32  # 256 bits, matches HS256 minimum


def get_secret() -> bytes:
    """Fetch the JWT signing secret. Empty bytes if not set yet.

    Returns:
        32 raw bytes (decoded from hex). Empty if `set_secret` was never
        called on this machine (caller should treat empty as
        "needs initialization").

    Raises:
        AuthError: keyring backend unavailable, or stored value is
            not valid hex.
    """
    try:
        value = keyring.get_password(KEYRING_SERVICE, KEYRING_USER)
    except keyring.errors.KeyringError as exc:
        raise AuthError(
            code="keyring_unavailable",
            detail=(
                f"OS keyring backend unavailable ({type(exc).__name__}: {exc}). "
                "Please install and start a keyring daemon "
                "(Linux: gnome-keyring-daemon or kwallet; macOS/Windows: built-in)."
            ),
            status_code=500,
        ) from exc
    if not value:
        return b""
    try:
        return bytes.fromhex(value)
    except ValueError as exc:
        raise AuthError(
            code="keyring_corrupt",
            detail=(
                "Stored JWT secret is not valid hex; cannot recover. "
                "Re-run `llmwikify auth init --rotate-secret` to reset."
            ),
            status_code=500,
        ) from exc


def set_secret(secret: bytes | None = None) -> bytes:
    """Generate (or accept) a 32-byte secret and store in OS keyring.

    Args:
        secret: pre-generated bytes. If None, `secrets.token_bytes(32)` is
            used. MUST be at least SECRET_BYTES bytes (we truncate to
            SECRET_BYTES to be defensive against caller error).

    Returns:
        The bytes that were stored. Always exactly SECRET_BYTES long.

    Raises:
        AuthError: keyring backend unavailable, or `secret` is the wrong
            type / length.
    """
    if secret is None:
        secret = secrets.token_bytes(SECRET_BYTES)
    if not isinstance(secret, (bytes, bytearray)):
        raise AuthError(
            code="keyring_secret_type",
            detail="secret must be bytes",
            status_code=500,
        )
    if len(secret) < SECRET_BYTES:
        raise AuthError(
            code="keyring_secret_length",
            detail=f"secret must be at least {SECRET_BYTES} bytes (got {len(secret)})",
            status_code=500,
        )
    secret = bytes(secret[:SECRET_BYTES])
    try:
        keyring.set_password(KEYRING_SERVICE, KEYRING_USER, secret.hex())
    except keyring.errors.KeyringError as exc:
        raise AuthError(
            code="keyring_unavailable",
            detail=(
                f"OS keyring backend unavailable ({type(exc).__name__}: {exc}). "
                "Please install and start a keyring daemon."
            ),
            status_code=500,
        ) from exc
    return secret


def require_secret() -> bytes:
    """Get the JWT secret, raising if not initialized.

    Returns:
        32 raw bytes.

    Raises:
        AuthError: not initialized, or keyring unavailable / corrupt.
    """
    secret = get_secret()
    if not secret:
        raise AuthError(
            code="auth_not_initialized",
            detail=(
                "JWT secret not found. Run `llmwikify auth init --email <you@example.com>` "
                "first to create the first admin user and signing secret."
            ),
            status_code=500,
        )
    return secret
