"""Research Engine — ReAct loop orchestrator with adaptive reasoning.

Replaces the fixed 7-stage sequential flow with an adaptive ReAct
(Reason → Act → Observe → loop) agent that dynamically decides what
to do next based on intermediate results.
"""

from __future__ import annotations

import json
import time
import logging
from collections.abc import AsyncIterator
from dataclasses import dataclass, field
from typing import Any

from ..adapters import StreamableLLMClient
from ..db import AgentDatabase
from ..providers.registry import create_llm
from .analyzer import SourceAnalyzer
from .config import merge_research_config
from .gatherer import SourceGatherer
from .report import ReportGenerator
from .review import ResearchReviewer, ResearchRevisor
from .session import ResearchSessionManager
from .synthesizer import ResearchSynthesizer
from .web_search import WebSearch
from .quality_gate import QualityGate

logger = logging.getLogger(__name__)


@dataclass
class ResearchState:
    """Mutable state for the ReAct research loop."""

    session_id: str = ""
    query: str = ""

    # Round tracking
    round: int = 0
    max_rounds: int = 5
    phase: str = ""  # planning | gathering | analyzing | synthesizing | reporting | reviewing | done

    # Data accumulators
    sub_queries: list[dict[str, Any]] = field(default_factory=list)
    sources: list[dict[str, Any]] = field(default_factory=list)
    synthesis: dict[str, Any] | None = None
    report_md: str | None = None
    review: dict[str, Any] | None = None

    # Quality tracking
    quality_score: int = 0
    knowledge_gaps: list[str] = field(default_factory=list)
    contradictions: list[str] = field(default_factory=list)
    issues: list[str] = field(default_factory=list)

    # Budget
    total_llm_calls: int = 0
    total_sources: int = 0
    total_sub_queries: int = 0
    budget_remaining: float = 1.0

    # Control signals
    cancelled: bool = False
    paused: bool = False

    # Interpreted observations (generated by _observe)
    observations: list[str] = field(default_factory=list)


class ResearchEngine:
    """Orchestrates the ReAct research loop.

    Instead of a fixed sequential pipeline, the agent reasons about what
    to do next based on intermediate results, enabling:
    - Adaptive re-planning when knowledge gaps are detected
    - Self-correcting review loop with re-gathering
    - Budget-aware iteration with configurable round limits
    """

    def __init__(
        self,
        wiki: Any,
        db: AgentDatabase,
        llm_client: StreamableLLMClient,
        config: dict[str, Any] | None = None,
    ):
        self.wiki = wiki
        self.db = db
        self.config = merge_research_config(config)
        self.session_manager = ResearchSessionManager(db)
        self._timeout_seconds = self.config.get("research_timeout_minutes", 30) * 60
        self._start_time: float = 0

        # Model layering
        self._default_llm = llm_client
        self._planning_llm = self._resolve_model("planning_model") or llm_client
        self._report_llm = self._resolve_model("report_model") or llm_client

        # ReAct config
        self._max_react_rounds = self.config.get("max_react_rounds", 5)
        self._quality_threshold = self.config.get("quality_threshold", 7)
        self._max_replan = self.config.get("max_replan_attempts", 2)

        # Quality gate
        self._quality_gate = QualityGate(self.config)

    def _resolve_model(self, config_key: str) -> StreamableLLMClient | None:
        model_cfg = self.config.get(config_key)
        if not model_cfg:
            return None
        try:
            return create_llm(model_cfg)
        except Exception as e:
            logger.warning("Failed to resolve %s: %s, using default LLM", config_key, e)
            return None

    def _check_timeout(self) -> None:
        if self._start_time > 0:
            elapsed = time.monotonic() - self._start_time
            if elapsed > self._timeout_seconds:
                raise TimeoutError(f"Research timed out after {elapsed:.0f}s (limit: {self._timeout_seconds}s)")

    async def run(self, session_id: str, query: str, resume: bool = False) -> AsyncIterator[dict[str, Any]]:
        """Execute the ReAct research loop, yielding SSE events."""
        self.session_manager.session_id = session_id
        self._start_time = time.monotonic()

        try:
            async for event in self._react_loop(session_id, query, resume):
                self._check_timeout()
                yield event
        except TimeoutError:
            self.session_manager.update_status(session_id, "timeout", "timeout", -1)
            yield {"type": "error", "error": f"Research timed out after {self._timeout_seconds}s"}
        except Exception:
            raise
        finally:
            # Safety net: if generator is killed (e.g. client disconnect / GeneratorExit),
            # ensure session is never left in a stale running/gathering state
            try:
                current = self.db.get_research_session(session_id)
                if current and current.get("status") not in ("done", "cancelled", "paused", "timeout", "error"):
                    logger.warning("Session %s generator exited in stale state '%s', marking as error",
                                   session_id, current.get("status"))
                    self.session_manager.update_status(session_id, "error", current.get("current_step", "unknown"), -1)
            except Exception:
                pass

    # ─── ReAct Core Loop ───────────────────────────────────────────────

    async def _react_loop(
        self, session_id: str, query: str, resume: bool
    ) -> AsyncIterator[dict[str, Any]]:
        """Main ReAct loop: Reason → Act → Observe → repeat."""
        state = ResearchState(
            session_id=session_id,
            query=query,
            max_rounds=self._max_react_rounds,
        )

        # Load existing state on resume
        if resume:
            self._load_resume_state(state)

        try:
            while state.phase != "done":
                self._check_timeout()
                elapsed = time.monotonic() - self._start_time
                state.budget_remaining = max(0, 1 - elapsed / self._timeout_seconds)

                # ── Check cancel/pause signals from DB ──
                self._check_control_signals(state)
                if state.cancelled:
                    yield {"type": "cancelled", "round": state.round, "phase": state.phase}
                    self.session_manager.update_status(session_id, "cancelled", state.phase, -1)
                    break
                if state.paused:
                    yield {"type": "paused", "round": state.round, "phase": state.phase}
                    self.session_manager.update_status(session_id, "paused", state.phase, state.round)
                    break

                # ── REASON: decide next action (ReAct Thought) ──
                action = await self._reason(state)
                thought = getattr(state, "_last_thought", "")
                yield {
                    "type": "reasoning",
                    "action": action,
                    "thought": thought,
                    "round": state.round,
                    "phase": state.phase,
                }

                # ── ACT: execute action ──
                if action == "plan":
                    async for event in self._action_plan(state):
                        yield event
                elif action == "gather":
                    async for event in self._action_gather(state):
                        yield event
                elif action == "analyze":
                    async for event in self._action_analyze(state):
                        yield event
                elif action == "synthesize":
                    async for event in self._action_synthesize(state):
                        yield event
                elif action == "report":
                    async for event in self._action_report(state):
                        yield event
                elif action == "review":
                    async for event in self._action_review(state):
                        yield event
                elif action == "revise":
                    async for event in self._action_revise(state):
                        yield event
                elif action == "done":
                    async for event in self._action_done(state):
                        yield event
                    break
                else:
                    # Unknown action → default to done
                    logger.warning("Unknown action %s, defaulting to done", action)
                    async for event in self._action_done(state):
                        yield event
                    break

                # ── OBSERVE: update state from DB ──
                self._observe(state)

                # ── Quality gate check ──
                if self.config.get("gate_enabled", True):
                    gate_result = self._evaluate_gate(state)
                    if gate_result:
                        state.observations.append(
                            f"[质量门禁] {gate_result.gate_name}: {gate_result.summary}"
                        )
                        if not gate_result.passed:
                            state.observations.append(
                                f"⚠ 门禁未通过，建议: {gate_result.suggestion}"
                            )
                            # Force transition: if gate fails after gathering and we have sources,
                            # override action to analyze instead of stuck in gather loop
                            if (state.phase == "gathering"
                                    and len(state.sources) >= self.config.get("gate_min_sources", 3)
                                    and action == "gather"):
                                action = "analyze"
                                logger.info("Gate %s failed, forcing analyze (have %d sources)",
                                            gate_result.gate_name, len(state.sources))

                # ── Track iteration count ──
                state.round += 1

                # ── Evaluate: check exit conditions ──
                if state.round >= state.max_rounds:
                    yield {"type": "round_max", "round": state.round, "message": f"Reached max rounds ({state.max_rounds})"}
                    async for event in self._action_done(state):
                        yield event
                    break
        except Exception as e:
            # Catch-all: ensure DB status is always updated on unexpected errors
            logger.error("ReAct loop error for session %s: %s", session_id, e, exc_info=True)
            self.session_manager.update_status(session_id, "error", state.phase or "unknown", -1)
            yield {"type": "error", "error": str(e)}
        finally:
            # Ensure session is never left in a stuck state (e.g. client disconnect / GeneratorExit)
            try:
                current = self.db.get_research_session(session_id)
                if current and current.get("status") not in ("done", "cancelled", "paused", "timeout", "error"):
                    logger.warning("Session %s exited loop in stale state '%s', marking as error",
                                   session_id, current.get("status"))
                    self.session_manager.update_status(session_id, "error", state.phase or "unknown", -1)
            except Exception:
                pass

    # ─── Reason Step ───────────────────────────────────────────────────

    async def _reason(self, state: ResearchState) -> str:
        """Decide next action based on current state.

        Uses LLM for reasoning (ReAct Thought step), falls back to deterministic rules.
        """
        # LLM-based reasoning first (true ReAct Thought)
        try:
            return await self._llm_reason(state)
        except Exception as e:
            logger.warning("LLM reasoning failed: %s, using rule-based fallback", e)
            return self._rule_based_reason(state) or "done"

    def _rule_based_reason(self, state: ResearchState) -> str | None:
        """Deterministic decision rules as fallback."""
        # Error state → done (let LLM override if it wants to retry)
        if state.phase == "error":
            return "done"

        # No sub-queries yet → plan
        if not state.sub_queries:
            return "plan"

        # Not all gathered → gather (skip failed sub-queries)
        gathered_ids = {s.get("sub_query_id") for s in state.sources}
        ungathered = [
            sq for sq in state.sub_queries
            if sq["id"] not in gathered_ids and sq.get("status") != "failed"
        ]
        if ungathered:
            return "gather"

        # Not all analyzed → analyze
        sources = self.db.get_sources(state.session_id)
        unanalyzed = [s for s in sources if not s.get("analysis")]
        if unanalyzed:
            return "analyze"

        # No synthesis yet → synthesize
        if state.synthesis is None:
            return "synthesize"

        # Knowledge gaps detected + budget allows + replan attempts left → replan
        if (state.knowledge_gaps
                and state.budget_remaining > 0.15
                and state.round < state.max_replan + 1):
            return "plan"

        # No report yet → report
        if state.report_md is None:
            return "report"

        # Report exists, not reviewed → review
        if state.review is None:
            return "review"

        # Review passed → done
        if state.review and state.review.get("approved"):
            return "done"

        # Review failed + rounds remaining → revise
        if state.round < state.max_rounds:
            return "revise"

        # Default → done
        return "done"

    async def _llm_reason(self, state: ResearchState) -> str:
        """Use LLM to decide next action with chain-of-thought reasoning."""
        import asyncio
        import json as json_mod

        analyzed_count = sum(1 for s in state.sources if s.get("analysis"))
        failed_sq = sum(1 for sq in state.sub_queries if sq.get("status") == "failed")

        # Build observation context from interpreted observations
        obs_text = "\n".join(f"  - {o}" for o in state.observations) if state.observations else "  (none)"

        messages = [
            {"role": "system", "content": (
                "You are a research orchestrator using ReAct reasoning.\n"
                "Based on the current state, provide your reasoning and decide the next action.\n\n"
                "Return a JSON object with:\n"
                '- "thought": Your reasoning about what to do next and why (1-2 sentences)\n'
                '- "action": One of: plan, gather, analyze, synthesize, report, review, revise, done\n\n'
                "Rules:\n"
                "- If sub-queries exist but not all are gathered → gather\n"
                "- If sources exist but not all analyzed → analyze\n"
                "- If all analyzed but no synthesis → synthesize\n"
                "- If synthesis shows knowledge gaps and budget allows → plan (replan)\n"
                "- If report exists but not reviewed → review\n"
                "- If review failed and rounds remain → revise\n"
                "- If all done and quality acceptable → done\n"
            )},
            {"role": "user", "content": (
                f"Research topic: {state.query}\n"
                f"Round: {state.round}/{state.max_rounds}\n"
                f"Phase: {state.phase or 'starting'}\n"
                f"Quality score: {state.quality_score}/10\n"
                f"Budget remaining: {state.budget_remaining:.0%}\n\n"
                f"Sub-queries: {len(state.sub_queries)} ({failed_sq} failed)\n"
                f"Sources gathered: {len(state.sources)}\n"
                f"Sources analyzed: {analyzed_count}\n"
                f"Report exists: {state.report_md is not None}\n"
                f"Review exists: {state.review is not None}\n\n"
                f"Observations:\n{obs_text}\n\n"
                "What should I do next? Return JSON."
            )},
        ]

        def _call():
            return self._default_llm.chat(messages, max_tokens=200, temperature=0.1)

        raw = await asyncio.to_thread(_call)
        raw = raw.strip()
        if raw.startswith("```"):
            raw = raw.split("\n", 1)[1] if "\n" in raw else raw[3:]
            if raw.endswith("```"):
                raw = raw[:-3]
            raw = raw.strip()

        result = json_mod.loads(raw)
        action = result.get("action", "done")
        thought = result.get("thought", "")

        valid = {"plan", "gather", "analyze", "synthesize", "report", "review", "revise", "done"}
        if action not in valid:
            action = "done"

        # Store thought for SSE event (set on state so _react_loop can yield it)
        state._last_thought = thought

        return action

    # ─── Control Signal Check ─────────────────────────────────────────

    def _check_control_signals(self, state: ResearchState) -> None:
        """Check DB for cancel/pause signals from API layer."""
        try:
            session = self.db.get_research_session(state.session_id)
            if session:
                db_status = session.get("status", "")
                if db_status == "cancelling":
                    state.cancelled = True
                elif db_status == "pausing":
                    state.paused = True
        except Exception as e:
            logger.debug("Control signal check failed: %s", e)

    # ─── Observe Step ──────────────────────────────────────────────────

    def _observe(self, state: ResearchState) -> None:
        """Refresh state from DB and generate interpreted observations after each action."""
        state.sources = self.db.get_sources(state.session_id) or []
        state.sub_queries_raw = self.db.get_sub_queries(state.session_id) or []

        # Rebuild sub_queries list from DB
        state.sub_queries = [
            {"id": sq["id"], "query": sq["query"], "source_type": sq["source_type"],
             "url": sq.get("url"), "status": sq.get("status", "pending")}
            for sq in state.sub_queries_raw
        ]

        state.total_sources = len(state.sources)
        state.total_sub_queries = len(state.sub_queries)

        # Extract knowledge gaps from synthesis
        if state.synthesis:
            state.knowledge_gaps = state.synthesis.get("knowledge_gaps", [])
            state.contradictions = state.synthesis.get("contradictions", [])

        # Generate interpreted observations for the reasoner
        state.observations = []

        # Source quality distribution
        analyzed = [s for s in state.sources if s.get("analysis")]
        if analyzed:
            scores = [s.get("analysis", {}).get("quality_assessment", {}).get("credibility", 5) for s in analyzed]
            avg = sum(scores) / len(scores) if scores else 0
            state.observations.append(
                f"Average source credibility: {avg:.1f}/10 ({len(analyzed)}/{len(state.sources)} analyzed)"
            )

        # Failed sub-queries
        failed = [sq for sq in state.sub_queries if sq.get("status") == "failed"]
        if failed:
            state.observations.append(
                f"{len(failed)} sub-queries failed: {[sq['query'] for sq in failed[:3]]}"
            )

        # Source type distribution
        type_counts: dict[str, int] = {}
        for s in state.sources:
            t = s.get("source_type", "unknown")
            type_counts[t] = type_counts.get(t, 0) + 1
        if type_counts:
            state.observations.append(f"Source types: {type_counts}")

        # Wiki vs web ratio
        wiki_count = type_counts.get("wiki", 0)
        web_count = type_counts.get("web", 0)
        if wiki_count + web_count > 0:
            state.observations.append(
                f"Local wiki: {wiki_count} sources, Web: {web_count} sources"
            )

        # Key quality assessment
        analyzed = [s for s in state.sources if s.get("analysis")]
        if analyzed:
            cred_scores = [
                s.get("analysis", {}).get("quality_assessment", {}).get("credibility", 5)
                for s in analyzed
            ]
            avg_cred = sum(cred_scores) / len(cred_scores)
            if avg_cred < 5:
                state.observations.append(f"⚠ 平均可信度偏低 ({avg_cred:.1f}/10)，建议获取更高质量源")
            elif avg_cred >= 7:
                state.observations.append(f"✓ 源质量良好 (平均 {avg_cred:.1f}/10)")

        if len(state.knowledge_gaps) > 3:
            state.observations.append(
                f"⚠ {len(state.knowledge_gaps)} 个知识缺口，可能影响报告完整性"
            )

    # ─── Quality Gate Evaluation ────────────────────────────────────────

    def _evaluate_gate(self, state: ResearchState):
        """Evaluate quality gate based on current phase."""
        gate = self._quality_gate
        if state.phase == "gathering":
            return gate.check_after_gathering(state.sources, state.sub_queries)
        elif state.phase == "analyzing":
            return gate.check_after_analysis(state.sources)
        elif state.phase == "synthesizing":
            return gate.check_after_synthesis(state.synthesis)
        elif state.phase == "reporting":
            return gate.check_before_report(state.synthesis, state.sources)
        return None

    # ─── Action Implementations ────────────────────────────────────────

    async def _action_plan(self, state: ResearchState) -> AsyncIterator[dict[str, Any]]:
        """Plan sub-queries (initial or replanning for gaps)."""
        state.phase = "planning"
        self.session_manager.update_status(state.session_id, "planning", "planning", None)
        yield self._step_event("planning", f"Planning sub-queries (round {state.round})...")

        # Decide: initial plan or gap-focused replan
        if state.knowledge_gaps and state.sub_queries:
            yield {"type": "gap_detected", "gaps": state.knowledge_gaps, "round": state.round}
            sub_queries = await self._plan_for_gaps(state.query, state.knowledge_gaps)
        else:
            sub_queries = await self._plan_sub_queries(state.query)

        # Deduplicate against existing
        existing_queries = {sq["query"].lower().strip() for sq in state.sub_queries}
        new_queries = [sq for sq in sub_queries if sq["query"].lower().strip() not in existing_queries]

        for sq in new_queries[:5]:  # Limit per round
            sq_id = self.session_manager.add_sub_query(
                state.session_id, sq["query"], sq["source_type"], sq.get("url")
            )
            sq["id"] = sq_id
            state.sub_queries.append(sq)
            yield {
                "type": "sub_query_created",
                "sub_query_id": sq_id,
                "query": sq["query"],
                "source_type": sq["source_type"],
                "url": sq.get("url"),
            }

        yield {"type": "progress", "progress": 0.1, "message": f"Round {state.round}: {len(new_queries)} new sub-queries"}

    async def _action_gather(self, state: ResearchState) -> AsyncIterator[dict[str, Any]]:
        """Gather sources for ungathered sub-queries."""
        state.phase = "gathering"
        self.session_manager.update_status(state.session_id, "gathering", "gathering", None)
        yield self._step_event("gathering", "Gathering sources...")

        gathered_ids = {s.get("sub_query_id") for s in state.sources}
        remaining = [sq for sq in state.sub_queries if sq["id"] not in gathered_ids]

        if remaining:
            gatherer = SourceGatherer(self.wiki, self.db, self.session_manager, self.config)
            events = await gatherer.gather(remaining)
            for event in events:
                yield event

        sources = self.db.get_sources(state.session_id) or []
        yield {"type": "progress", "progress": 0.4, "message": f"Gathered {len(sources)} sources total"}

        if not sources:
            self.session_manager.update_status(state.session_id, "error", "gathering", -1)
            yield {"type": "error", "error": "No sources gathered. All sub-queries failed."}
            state.phase = "error"
            state.issues.append("No sources gathered — all sub-queries failed")

    async def _action_analyze(self, state: ResearchState) -> AsyncIterator[dict[str, Any]]:
        """Analyze unanalyzed sources."""
        state.phase = "analyzing"
        self.session_manager.update_status(state.session_id, "analyzing", "analyzing", None)
        yield self._step_event("analyzing", "Analyzing sources...")

        sources = self.db.get_sources(state.session_id) or []
        unanalyzed = [s for s in sources if not s.get("analysis")]

        if unanalyzed:
            analyzer = SourceAnalyzer(self.wiki, self.session_manager, self.config)
            events = await analyzer.analyze_sources(unanalyzed)
            for event in events:
                yield event

        yield {"type": "progress", "progress": 0.55, "message": "Analysis complete"}

    async def _action_synthesize(self, state: ResearchState) -> AsyncIterator[dict[str, Any]]:
        """Synthesize findings from analyzed sources."""
        state.phase = "synthesizing"
        self.session_manager.update_status(state.session_id, "synthesizing", "synthesizing", None)
        yield self._step_event("synthesizing", "Synthesizing cross-source findings...")

        sources = self.db.get_sources(state.session_id) or []
        synthesizer = ResearchSynthesizer(self.wiki, self.config)
        state.synthesis = await synthesizer.synthesize(sources, query=state.query)
        state.knowledge_gaps = state.synthesis.get("knowledge_gaps", [])
        state.contradictions = state.synthesis.get("contradictions", [])

        # Persist synthesis for resume
        import json as _json
        self.session_manager.update_status(
            state.session_id, "synthesizing", "synthesizing", None,
            iteration_round=state.round,
            synthesis_json=_json.dumps(state.synthesis),
        )

        yield {"type": "synthesis_complete", "synthesis": {
            "reinforced_claims": state.synthesis.get("reinforced_claims", []),
            "contradictions": state.synthesis.get("contradictions", []),
            "knowledge_gaps": state.synthesis.get("knowledge_gaps", []),
            "new_entities": state.synthesis.get("new_entities", []),
        }}
        yield {"type": "progress", "progress": 0.65, "message": "Synthesis complete"}

    async def _action_report(self, state: ResearchState) -> AsyncIterator[dict[str, Any]]:
        """Generate research report."""
        state.phase = "reporting"
        self.session_manager.update_status(state.session_id, "report", "report", None)
        yield self._step_event("report", "Generating research report...")

        sources = self.db.get_sources(state.session_id) or []
        generator = ReportGenerator(self.wiki, self._report_llm, self.config)
        try:
            state.report_md = await generator.generate(state.query, sources, state.synthesis or {})
            yield {"type": "progress", "progress": 0.75, "message": "Report generated"}
        except Exception as e:
            logger.error("Report generation failed: %s", e)
            yield {"type": "error", "error": f"Report generation failed: {e}"}
            self.session_manager.update_status(state.session_id, "error", "report", -1)
            state.phase = "error"
            state.issues.append(f"Report generation failed: {e}")

    async def _action_review(self, state: ResearchState) -> AsyncIterator[dict[str, Any]]:
        """Review report quality."""
        state.phase = "reviewing"
        self.session_manager.update_status(state.session_id, "reviewing", "reviewing", None)
        yield self._step_event("review", "Reviewing report quality...")

        sources = self.db.get_sources(state.session_id) or []
        reviewer = ResearchReviewer(self.wiki, self._default_llm, self.config)
        try:
            state.review = await reviewer.review(state.query, state.report_md or "", sources)
        except Exception as e:
            logger.error("Report review failed: %s", e)
            state.review = {"approved": False, "score": 0, "issues": [f"Review failed: {e}"], "feedback": ""}
        state.quality_score = state.review.get("score", 0)
        state.issues = state.review.get("issues", [])

        # Persist review for resume
        import json as _json
        self.session_manager.update_status(
            state.session_id, "reviewing", "reviewing", None,
            iteration_round=state.round,
            review_json=_json.dumps(state.review),
        )

        if state.review.get("approved"):
            yield {
                "type": "review_passed",
                "round": state.round,
                "score": state.quality_score,
                "feedback": state.review.get("feedback", ""),
            }
        else:
            yield {
                "type": "review_issues",
                "round": state.round,
                "score": state.quality_score,
                "issues": state.issues,
            }

    async def _action_revise(self, state: ResearchState) -> AsyncIterator[dict[str, Any]]:
        """Revise report based on review feedback."""
        yield self._step_event("revise", "Revising report...")

        sources = self.db.get_sources(state.session_id) or []
        revisor = ResearchRevisor(self.wiki, self._report_llm, self.config)
        try:
            state.report_md = await revisor.revise(state.report_md or "", state.issues, sources)
            # Reset review so it gets re-evaluated
            state.review = None
            yield {"type": "progress", "progress": 0.85, "message": "Report revised"}
        except Exception as e:
            logger.error("Report revision failed: %s", e)
            yield {"type": "error", "error": f"Report revision failed: {e}"}

    async def _action_done(self, state: ResearchState) -> AsyncIterator[dict[str, Any]]:
        """Finalize research session."""
        state.phase = "done"
        sources = self.db.get_sources(state.session_id) or []

        self.session_manager.update_status(state.session_id, "done", "done", 1.0, iteration_round=state.round)
        self.session_manager.finalize(state.session_id, {
            "markdown": state.report_md,
            "query": state.query,
            "quality_score": state.quality_score,
            "rounds": state.round,
            "synthesis_summary": {
                "reinforced_claims": len((state.synthesis or {}).get("reinforced_claims", [])),
                "contradictions": len((state.synthesis or {}).get("contradictions", [])),
                "knowledge_gaps": len(state.knowledge_gaps),
            },
            "sources": [
                {"id": s["id"], "title": s.get("title", ""), "url": s.get("url", ""), "source_type": s.get("source_type", "")}
                for s in sources
            ],
        })

        yield {
            "type": "done",
            "report": {
                "query": state.query,
                "markdown": state.report_md,
                "sources": [
                    {"id": s["id"], "title": s.get("title", ""), "url": s.get("url", ""), "source_type": s.get("source_type", "")}
                    for s in sources
                ],
                "synthesis_summary": {
                    "reinforced_claims": len((state.synthesis or {}).get("reinforced_claims", [])),
                    "contradictions": len((state.synthesis or {}).get("contradictions", [])),
                    "knowledge_gaps": len(state.knowledge_gaps),
                },
                "rounds": state.round,
                "quality_score": state.quality_score,
            },
        }

    # ─── Planning Helpers ──────────────────────────────────────────────

    async def _plan_sub_queries(self, query: str) -> list[dict[str, Any]]:
        """Decompose the research topic into sub-queries using planning_model."""
        from ....core.prompt_registry import PromptRegistry
        registry = PromptRegistry(provider="openai")

        # Proactively search local wiki for relevant articles
        local_wiki_matches = ""
        try:
            wiki_results = self.wiki.search(query, limit=5)
            if wiki_results:
                lines = []
                for r in wiki_results:
                    name = r.get("page_name", "")
                    snippet = r.get("snippet", "")
                    score = r.get("score", 0)
                    lines.append(f"- {name} (score: {score:.2f}): {snippet}")
                local_wiki_matches = "\n".join(lines)
        except Exception as e:
            logger.debug("Local wiki search failed: %s", e)

        wiki_index = ""
        if self.wiki.index_file.exists():
            wiki_index = self.wiki.index_file.read_text()[:3000]

        messages = registry.get_messages(
            "research_plan",
            query=query,
            wiki_index=wiki_index[:2000] if wiki_index else "",
            local_wiki_matches=local_wiki_matches,
        )
        api_params = registry.get_api_params("research_plan")

        try:
            import asyncio
            import json as json_mod

            def _call_llm():
                raw = self._planning_llm.chat(
                    messages,
                    json_mode=api_params.get("json_mode", True),
                    max_tokens=api_params.get("max_tokens", 2048),
                    temperature=api_params.get("temperature", 0.3),
                )
                return raw

            raw = await asyncio.to_thread(_call_llm)
            raw = raw.strip()
            if raw.startswith("```"):
                raw = raw.split("\n", 1)[1] if "\n" in raw else raw[3:]
                if raw.endswith("```"):
                    raw = raw[:-3]
                raw = raw.strip()
            result = json_mod.loads(raw)
            if not isinstance(result, list):
                result = []
        except Exception as e:
            logger.warning("Planning LLM failed: %s, using single query", e)
            result = [{"query": query, "source_type": "web", "url": ""}]

        max_sq = self.config.get("max_sub_queries", 20)
        sub_queries: list[dict[str, Any]] = []

        for item in result[:max_sq]:
            sq_type = item.get("source_type", "web")
            if sq_type not in ("web", "youtube", "wiki", "pdf"):
                sq_type = "web"
            sub_queries.append({
                "query": item.get("query", ""),
                "source_type": sq_type,
                "url": item.get("url"),
            })

        if not sub_queries:
            sub_queries.append({"query": query, "source_type": "web", "url": ""})

        return sub_queries

    async def _plan_for_gaps(self, query: str, gaps: list[str]) -> list[dict[str, Any]]:
        """Generate sub-queries to fill knowledge gaps."""
        import asyncio
        import json as json_mod

        gaps_text = "\n".join(f"- {gap}" for gap in gaps[:5])

        # Proactively search local wiki for gap-related content
        local_wiki_matches = ""
        try:
            gap_query = f"{query} {' '.join(gaps[:3])}"
            wiki_results = self.wiki.search(gap_query, limit=3)
            if wiki_results:
                lines = []
                for r in wiki_results:
                    name = r.get("page_name", "")
                    snippet = r.get("snippet", "")
                    lines.append(f"- {name}: {snippet}")
                local_wiki_matches = "\n".join(lines)
        except Exception as e:
            logger.debug("Local wiki search for gaps failed: %s", e)

        wiki_context = ""
        if local_wiki_matches:
            wiki_context = f"\n\nExisting wiki articles that may help fill gaps:\n{local_wiki_matches}\nUse source_type \"wiki\" for these if relevant."

        messages = [
            {"role": "system", "content": (
                "You are a research planner. Generate focused sub-queries to fill knowledge gaps. "
                "Return a JSON array of objects with 'query', 'source_type', and 'url' fields. "
                "source_type should be 'web', 'pdf', 'youtube', or 'wiki'. "
                "Use 'wiki' when existing wiki articles are relevant (see below). "
                "Generate 1-3 sub-queries per gap, maximum 5 total."
            )},
            {"role": "user", "content": (
                f"Research topic: {query}\n\n"
                f"Knowledge gaps to fill:\n{gaps_text}"
                f"{wiki_context}\n\n"
                "Generate sub-queries now. Return ONLY a JSON array."
            )},
        ]

        try:
            def _call():
                return self._planning_llm.chat(messages, json_mode=True, max_tokens=1024, temperature=0.3)

            raw = await asyncio.to_thread(_call)
            raw = raw.strip()
            if raw.startswith("```"):
                raw = raw.split("\n", 1)[1] if "\n" in raw else raw[3:]
                if raw.endswith("```"):
                    raw = raw[:-3]
                raw = raw.strip()
            result = json_mod.loads(raw)
            if not isinstance(result, list):
                result = []
        except Exception as e:
            logger.warning("Gap planning LLM failed: %s", e)
            result = [{"query": f"{query} {gaps[0]}", "source_type": "web", "url": ""}] if gaps else []

        sub_queries = []
        for item in result[:5]:
            sq_type = item.get("source_type", "web")
            if sq_type not in ("web", "youtube", "wiki", "pdf"):
                sq_type = "web"
            sub_queries.append({
                "query": item.get("query", ""),
                "source_type": sq_type,
                "url": item.get("url"),
            })

        return sub_queries

    # ─── Resume Helpers ────────────────────────────────────────────────

    def _load_resume_state(self, state: ResearchState) -> None:
        """Load existing session state for resume."""
        session = self.db.get_research_session(state.session_id)
        if not session:
            return

        state.round = session.get("iteration_round", 1)
        state.max_rounds = session.get("max_rounds", self._max_react_rounds)
        state.quality_score = session.get("quality_score", 0)

        gaps_raw = session.get("knowledge_gaps")
        if gaps_raw:
            try:
                state.knowledge_gaps = json.loads(gaps_raw)
            except (json.JSONDecodeError, TypeError):
                state.knowledge_gaps = []

        # Load existing sub-queries and sources
        existing_sqs = self.db.get_sub_queries(state.session_id) or []
        state.sub_queries = [
            {"id": sq["id"], "query": sq["query"], "source_type": sq["source_type"],
             "url": sq.get("url"), "status": sq.get("status", "pending")}
            for sq in existing_sqs
        ]
        state.sources = self.db.get_sources(state.session_id) or []

        # Determine phase from current_step
        current_step = session.get("current_step", "planning")
        state.phase = current_step if current_step not in ("done", "error") else ""

        # If we have a report, set it
        result = session.get("result")
        if result:
            try:
                parsed = json.loads(result)
                state.report_md = parsed.get("markdown")
            except (json.JSONDecodeError, TypeError):
                state.report_md = result

        # Restore synthesis for resume
        synthesis_raw = session.get("synthesis_json")
        if synthesis_raw:
            try:
                state.synthesis = json.loads(synthesis_raw)
                state.knowledge_gaps = state.synthesis.get("knowledge_gaps", [])
                state.contradictions = state.synthesis.get("contradictions", [])
            except (json.JSONDecodeError, TypeError):
                pass

        # Restore review for resume
        review_raw = session.get("review_json")
        if review_raw:
            try:
                state.review = json.loads(review_raw)
                state.quality_score = state.review.get("score", 0)
                state.issues = state.review.get("issues", [])
            except (json.JSONDecodeError, TypeError):
                pass

        logger.info("Resuming session %s from %s (round %d)", state.session_id, current_step, state.round)

    # ─── Utilities ─────────────────────────────────────────────────────

    def _step_event(self, step: str, message: str) -> dict[str, Any]:
        return {"type": "step", "step": step, "message": message, "session_id": self.session_manager.session_id}
