"""Wiki core business logic."""

import json
import re
import os
from pathlib import Path
from typing import Optional, List, Dict, Any
from datetime import datetime, timezone

from .index import WikiIndex
from ..extractors import extract
from ..config import load_config, get_directory, get_file_path, get_db_path


class Wiki:
    """Main Wiki manager."""
    
    def __init__(self, root: Path, config: Optional[dict] = None):
        self.root = root.resolve()
        
        # Load configuration (external file or built-in defaults)
        self.config = config or load_config(self.root)
        
        # Set up directory structure from config
        self.raw_dir = get_directory(self.root, 'raw', self.config)
        self.wiki_dir = get_directory(self.root, 'wiki', self.config)
        
        # Set up file paths from config
        self.index_file = get_file_path(self.root, 'index', self.config)
        self.log_file = get_file_path(self.root, 'log', self.config)
        self.db_path = get_db_path(self.root, self.config)
        
        # Reference index path
        ref_index_name = self.config.get('reference_index', {}).get('name', 'reference_index.json')
        self._ref_index_path: Optional[Path] = None
        self._ref_index_name = ref_index_name
        
        # Orphan detection configuration
        orphan_config = self.config.get('orphan_detection', {})
        self._default_exclude_patterns = orphan_config.get('default_exclude_patterns', [])
        self._user_exclude_patterns = orphan_config.get('exclude_patterns', [])
        self._exclude_frontmatter_keys = orphan_config.get('exclude_frontmatter', ['redirect_to'])
        self._archive_dirs = orphan_config.get('archive_directories', ['archive', 'logs', 'history'])
        
        # Performance settings
        perf_config = self.config.get('performance', {})
        self._batch_size = perf_config.get('batch_size', 100)
        
        self._index: Optional[WikiIndex] = None
    
    @property
    def ref_index_path(self) -> Path:
        """Path to reference index JSON."""
        if self._ref_index_path is None:
            self._ref_index_path = self.wiki_dir / self._ref_index_name
        return self._ref_index_path
    
    @property
    def index(self) -> WikiIndex:
        """Lazy-load WikiIndex."""
        if self._index is None:
            self._index = WikiIndex(self.db_path)
        return self._index
    
    def is_initialized(self) -> bool:
        """Check if wiki is initialized."""
        return (self.raw_dir.exists() and 
                self.wiki_dir.exists() and 
                self.db_path.exists())
    
    def init(self, agent: str = "claude") -> str:
        """Initialize wiki directory structure."""
        # Create directories
        self.raw_dir.mkdir(parents=True, exist_ok=True)
        self.wiki_dir.mkdir(parents=True, exist_ok=True)
        
        # Initialize database
        self.index.initialize()
        
        # Create index.md
        self.index_file.write_text(
            "# Wiki Index\n\n"
            f"Generated by llmwikify v{self._get_version()}\n\n"
            f"Agent: {agent}\n\n"
            "---\n\n"
            "## Pages\n\n"
            "*(No pages yet)*\n"
        )
        
        # Create log.md
        self.log_file.write_text(
            "# Wiki Log\n\n"
            f"Initialized: {self._now()}\n\n"
            "---\n"
        )
        
        # Create config example
        config_example = self.root / self.config.get('files', {}).get('config_example', '.wiki-config.yaml.example')
        if not config_example.exists():
            config_example.write_text(
                "# Wiki Configuration\n"
                "# See docs/CONFIG_GUIDE.md for details\n\n"
                "# Override default constants\n"
                "# database:\n"
                "#   name: \".my-wiki.db\"\n\n"
                "# orphan_detection:\n"
                "#   exclude_patterns:\n"
                "#     - '^\\d{4}-\\d{2}-\\d{2}$'  # Dates\n"
                "#     - '^meeting-.*'             # Meeting notes\n"
                "#   archive_directories:\n"
                "#     - 'archive'\n"
                "#     - 'logs'\n"
            )
        
        return f"Wiki initialized at {self.root}"
    
    def ingest_source(self, source: str) -> dict:
        """Ingest a source file (PDF/URL/YouTube)."""
        try:
            result = extract(source, wiki_root=self.root)
            
            if not result.text:
                return {"error": "No content extracted"}
            
            # Create wiki page
            page_name = result.title or Path(source).stem
            content = f"# {page_name}\n\n{result.text}\n"
            
            self.write_page(page_name, content)
            
            return {
                "title": page_name,
                "source_type": result.source_type,
                "content_length": len(result.text),
            }
            
        except Exception as e:
            return {"error": str(e)}
    
    def write_page(self, page_name: str, content: str) -> str:
        """Write a wiki page."""
        page_path = self.wiki_dir / f"{page_name}.md"
        
        if page_path.exists():
            page_path.write_text(content)
            action = "Updated"
        else:
            page_path.write_text(content)
            action = "Created"
        
        # Update index
        rel_path = str(page_path.relative_to(self.wiki_dir))
        self.index.upsert_page(page_name, content, rel_path)
        
        return f"{action} page: {page_name}"
    
    def read_page(self, page_name: str) -> dict:
        """Read a wiki page."""
        page_path = self.wiki_dir / f"{page_name}.md"
        
        if not page_path.exists():
            return {"error": f"Page not found: {page_name}"}
        
        return {
            "page_name": page_name,
            "content": page_path.read_text(),
            "file": str(page_path),
        }
    
    def search(self, query: str, limit: int = 10) -> list:
        """Full-text search."""
        return self.index.search(query, limit)
    
    def lint(self) -> dict:
        """Health check the wiki."""
        issues = []
        
        # Check for broken links
        for page in self.wiki_dir.glob("*.md"):
            content = page.read_text()
            # Simple link checking logic
            links = re.findall(r'\[\[(.*?)\]\]', content)
            for link in links:
                target = link.split('|')[0].split('#')[0].strip()
                target_path = self.wiki_dir / f"{target}.md"
                if not target_path.exists():
                    issues.append({
                        "type": "broken_link",
                        "page": page.stem,
                        "link": target,
                        "file": str(page),
                    })
        
        # Check for orphan pages
        for page in self.wiki_dir.glob("*.md"):
            page_name = page.stem
            if page_name in ('index', 'log'):
                continue
            
            if self._should_exclude_orphan(page_name, page):
                continue
            
            inbound = self.index.get_inbound_links(page_name)
            if not inbound:
                issues.append({
                    "type": "orphan_page",
                    "page": page_name,
                    "file": str(page),
                })
        
        return {
            "total_pages": len(list(self.wiki_dir.glob("*.md"))),
            "issue_count": len(issues),
            "issues": issues,
        }
    
    def recommend(self) -> dict:
        """Generate smart recommendations."""
        missing_pages = []
        orphan_pages = []
        
        # Find missing pages (referenced but don't exist)
        link_counts = {}
        for page in self.wiki_dir.glob("*.md"):
            content = page.read_text()
            links = re.findall(r'\[\[(.*?)\]\]', content)
            for link in links:
                target = link.split('|')[0].split('#')[0].strip()
                if target not in ('index', 'log'):
                    link_counts[target] = link_counts.get(target, 0) + 1
        
        for target, count in link_counts.items():
            if count >= 2:  # Threshold for missing pages
                target_path = self.wiki_dir / f"{target}.md"
                if not target_path.exists():
                    missing_pages.append({
                        "page": target,
                        "reference_count": count,
                    })
        
        # Find orphan pages
        for page in self.wiki_dir.glob("*.md"):
            page_name = page.stem
            if page_name in ('index', 'log'):
                continue
            
            if self._should_exclude_orphan(page_name, page):
                continue
            
            inbound = self.index.get_inbound_links(page_name)
            if not inbound:
                orphan_pages.append({"page": page_name})
        
        return {
            "missing_pages": missing_pages,
            "orphan_pages": orphan_pages,
            "summary": {
                "total_missing_pages": len(missing_pages),
                "total_orphans": len(orphan_pages),
            },
        }
    
    def status(self) -> dict:
        """Get wiki status."""
        return {
            "initialized": self.is_initialized(),
            "root": str(self.root),
            "page_count": len(list(self.wiki_dir.glob("*.md"))),
            "source_count": len(list(self.raw_dir.glob("*"))),
            "indexed_pages": self.index.get_page_count() if self.is_initialized() else "N/A",
            "total_links": self.index.get_link_count() if self.is_initialized() else "N/A",
        }
    
    def append_log(self, operation: str, details: str) -> str:
        """Append entry to wiki log."""
        entry = f"## [{self._now()}] {operation} | {details}\n"
        with open(self.log_file, 'a') as f:
            f.write(entry)
        return "Logged"
    
    def build_index(self, auto_export: bool = True, output_path: Optional[Path] = None) -> dict:
        """Build reference index."""
        result = self.index.build_index_from_files(self.wiki_dir, batch_size=self._batch_size)
        
        if auto_export:
            export_path = output_path or self.ref_index_path
            self.index.export_json(export_path)
            result["json_export"] = str(export_path)
        
        return result
    
    def export_index(self, output_path: Path) -> dict:
        """Export reference index to JSON."""
        return self.index.export_json(output_path)
    
    def get_inbound_links(self, page_name: str) -> list:
        """Get pages that link to this page."""
        return self.index.get_inbound_links(page_name)
    
    def get_outbound_links(self, page_name: str) -> list:
        """Get pages that this page links to."""
        return self.index.get_outbound_links(page_name)
    
    def _should_exclude_orphan(self, page_name: str, page_path: Path) -> bool:
        """Check if a page should be excluded from orphan detection."""
        page_name_lower = page_name.lower()
        
        # Check default patterns
        for pattern in self._default_exclude_patterns:
            if re.match(pattern, page_name_lower):
                return True
        
        # Check user-configured patterns
        for pattern in self._user_exclude_patterns:
            if re.match(pattern, page_name_lower):
                return True
        
        # Check frontmatter
        if page_path.exists():
            content = page_path.read_text()
            for key in self._exclude_frontmatter_keys:
                if f"{key}:" in content:
                    return True
        
        # Check if in archive directory
        try:
            rel_path = page_path.relative_to(self.wiki_dir)
            for part in rel_path.parts:
                if part.lower() in self._archive_dirs:
                    return True
        except ValueError:
            pass
        
        return False
    
    @staticmethod
    def _slugify(text: str) -> str:
        """Convert text to URL-friendly slug."""
        text = text.lower().strip()
        text = re.sub(r'[^\w\s-]', '', text)
        text = re.sub(r'[-\s]+', '-', text)
        return text
    
    @staticmethod
    def _now() -> str:
        """Get current ISO timestamp."""
        return datetime.now(timezone.utc).isoformat().replace('+00:00', 'Z')
    
    @staticmethod
    def _get_version() -> str:
        """Get llmwikify version."""
        try:
            from .. import __version__
            return __version__
        except ImportError:
            return "0.11.0"
    
    def close(self):
        """Close database connections."""
        if self._index:
            self._index.close()
