/**
 * Reproduction - API client for /api/reproduction/* endpoints.
 *
 * v0.4.0: 5-phase pipeline orchestration. Mirrors autoresearch-api
 * structure (retry / SSE patterns) for consistency.
 *
 * Phases:
 *   1. extract   — read TradingStrategy wiki pages
 *   2. data      — fetch OHLCV via DataRouter (chain: cache+CH → CH → AKShare → synth)
 *   3. backtest  — run_backtest(Path A prewritten / Path B codegen)
 *   4. analyze   — write BacktestResult + Optimization wiki pages
 *   5. finalize  — mark done / error
 */

const API_BASE = '/api/reproduction';
const MAX_RETRIES = 2;
const RETRY_DELAY_MS = 3000;

function sleep(ms: number) { return new Promise(r => setTimeout(r, ms)); }

async function fetchWithRetry(
  url: string,
  init: RequestInit,
  method: string,
  reqBody?: string,
): Promise<Response> {
  let lastError: unknown;
  for (let attempt = 0; attempt <= MAX_RETRIES; attempt++) {
    let response: Response;
    try {
      response = await fetch(url, init);
    } catch (e) {
      lastError = e;
      if (attempt < MAX_RETRIES) { await sleep(RETRY_DELAY_MS); continue; }
      throw e;
    }
    if (response.ok) return response;

    const text = await response.text();
    let parsed: { error?: string; detail?: unknown };
    try { parsed = JSON.parse(text); } catch { parsed = {}; }
    const msg = parsed.error
      || (Array.isArray(parsed.detail) && parsed.detail[0]?.msg)
      || `Failed (${response.status})`;
    if (attempt < MAX_RETRIES && response.status >= 500) {
      await sleep(RETRY_DELAY_MS);
      continue;
    }
    throw new Error(msg);
  }
  throw lastError instanceof Error ? lastError : new Error('Max retries exceeded');
}

function authHeaders(): Record<string, string> {
  const token = (import.meta as unknown as { env: Record<string, string> }).env?.VITE_API_TOKEN;
  return token ? { Authorization: `Bearer ${token}` } : {};
}

// ─── Types ─────────────────────────────────────────────────────

export type SessionStatus =
  | 'pending'
  | 'extracting'
  | 'backtesting'
  | 'analyzing'
  | 'done'
  | 'error';

export interface ReproductionSession {
  id: string;
  wiki_id: string;
  paper_id: string;
  source_type: string;
  source_ref: string;
  symbol: string;
  start_date: string;
  end_date: string;
  status: SessionStatus;
  error: string | null;
  strategy_signal_type: string;
  strategy_params_json: string;
  created_at: string;
  updated_at: string;
}

export interface ReproductionArtifact {
  kind: string;
  wiki_page: string;
  meta: Record<string, unknown>;
  created_at: string;
}

export interface ReproductionEvent {
  event_type: string;
  payload_json: string;
  id: number;
  created_at: string;
}

export interface ReproductionMetrics {
  sharpe_ratio: number;
  max_drawdown: number;
  win_rate: number;
  total_return: number;
  final_cash: number;
  trades: number;
}

export interface StartReproductionRequest {
  wiki_id?: string;
  paper_id: string;
  source_type: 'pdf' | 'url';
  source_ref: string;
  symbol: string;
  start_date: string;
  end_date: string;
}

export interface StartReproductionResponse {
  session_id: string;
  status: SessionStatus;
  signal_type?: string;
  signal_params?: Record<string, unknown>;
  source?: string;
  metrics?: ReproductionMetrics;
  error?: string;
}

// ─── Public API ──────────────────────────────────────────────

/** Start a reproduction session. Runs the full 5-phase pipeline synchronously. */
export async function startReproduction(
  req: StartReproductionRequest,
): Promise<StartReproductionResponse> {
  const url = `${API_BASE}/start`;
  const body = JSON.stringify(req);
  const response = await fetchWithRetry(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...authHeaders() },
    body,
  }, 'POST', body);
  return response.json();
}

/** Get a session + recent events. */
export async function getReproduction(
  sessionId: string,
): Promise<{ session: ReproductionSession; events: ReproductionEvent[] }> {
  const url = `${API_BASE}/${sessionId}`;
  const response = await fetchWithRetry(url, {
    method: 'GET',
    headers: { ...authHeaders() },
  }, 'GET');
  return response.json();
}

/** List all artifacts (wiki pages) generated by a session. */
export async function listReproductionArtifacts(
  sessionId: string,
): Promise<{ session_id: string; artifacts: ReproductionArtifact[] }> {
  const url = `${API_BASE}/${sessionId}/artifacts`;
  const response = await fetchWithRetry(url, {
    method: 'GET',
    headers: { ...authHeaders() },
  }, 'GET');
  return response.json();
}

/** Delete a reproduction session. */
export async function deleteReproductionSession(sessionId: string): Promise<{ ok: boolean }> {
  const response = await fetchWithRetry(`${API_BASE}/${sessionId}`, {
    method: 'DELETE',
    headers: { ...authHeaders() },
  }, 'DELETE');
  return response.json();
}

/** List all reproduction sessions. */
export async function listReproductionSessions(
  status?: string,
): Promise<{ sessions: ReproductionSession[] }> {
  const url = status ? `${API_BASE}/list?status=${status}` : `${API_BASE}/list`;
  const response = await fetchWithRetry(url, {
    method: 'GET',
    headers: { ...authHeaders() },
  }, 'GET');
  return response.json();
}

// ─── Helpers ──────────────────────────────────────────────────

export function parseParams(json: string): Record<string, unknown> {
  if (!json) return {};
  try { return JSON.parse(json); } catch { return {}; }
}

export function parseEventPayload(json: string): Record<string, unknown> {
  if (!json) return {};
  try { return JSON.parse(json); } catch { return {}; }
}

export const FIVE_PHASES = [
  { key: 'extract',   label: '提取策略', num: 1, desc: '读 wiki TradingStrategy 页' },
  { key: 'data',      label: '拉取数据', num: 2, desc: 'OHLCV via DataRouter' },
  { key: 'backtest',  label: '回测',    num: 3, desc: 'run_backtest(Path A/B)' },
  { key: 'analyze',   label: '写 Wiki',  num: 4, desc: 'BacktestResult + Optimization' },
  { key: 'finalize',  label: '完成',    num: 5, desc: '归档' },
] as const;

export const STATUS_LABELS: Record<SessionStatus, { icon: string; color: string; text: string }> = {
  pending:     { icon: '◌', color: 'text-muted-foreground',  text: '待启动' },
  extracting:  { icon: '↓', color: 'text-primary',          text: '提取策略中' },
  backtesting: { icon: '◐', color: 'text-primary',          text: '回测中' },
  analyzing:   { icon: '◍', color: 'text-primary',          text: '写入 Wiki' },
  done:        { icon: '✓', color: 'text-green-400',        text: '已完成' },
  error:       { icon: '✗', color: 'text-red-400',          text: '失败' },
};

/** Map a backend event_type to the front-end phase it represents. */
export function eventToPhase(eventType: string): typeof FIVE_PHASES[number]['key'] | null {
  if (eventType === 'extract.done')   return 'extract';
  if (eventType === 'data.fetched')   return 'data';
  if (eventType === 'backtest.done')  return 'backtest';
  if (eventType === 'wiki.written')   return 'analyze';
  if (eventType === 'finalize.done')  return 'finalize';
  return null;
}