/**
 * ArtifactList — display wiki pages generated by a reproduction session.
 *
 * Each artifact links to its wiki page (BacktestResult / Optimization).
 */

import { ExternalLink, FileText, Settings } from 'lucide-react';
import type { ReproductionArtifact } from '../../lib/reproduction-api';

interface ArtifactListProps {
  artifacts: ReproductionArtifact[];
  onOpenPage?: (page: string) => void;
}

const KIND_ICONS: Record<string, typeof FileText> = {
  BacktestResult: FileText,
  Optimization: Settings,
};

const KIND_LABELS: Record<string, string> = {
  BacktestResult: '回测结果',
  Optimization: '优化建议',
};

export function ArtifactList({ artifacts, onOpenPage }: ArtifactListProps) {
  if (artifacts.length === 0) {
    return (
      <div className="text-xs text-muted-foreground text-center py-4">
        尚未生成产物
      </div>
    );
  }

  return (
    <div className="space-y-2">
      {artifacts.map((a) => {
        const Icon = KIND_ICONS[a.kind] || FileText;
        return (
          <button
            key={`${a.kind}-${a.wiki_page}`}
            onClick={() => onOpenPage?.(a.wiki_page)}
            className="w-full text-left p-3 bg-card border border-border rounded-lg
              hover:border-primary/40 transition-colors group"
          >
            <div className="flex items-center justify-between mb-1">
              <div className="flex items-center gap-2">
                <div className="w-7 h-7 rounded-md bg-primary/10 flex items-center justify-center">
                  <Icon className="w-3.5 h-3.5 text-primary" />
                </div>
                <div className="text-sm font-medium text-foreground">
                  {KIND_LABELS[a.kind] || a.kind}
                </div>
              </div>
              <ExternalLink className="w-3.5 h-3.5 text-muted-foreground
                group-hover:text-primary transition-colors" />
            </div>
            <div className="text-[11px] text-muted-foreground font-mono truncate pl-9">
              {a.wiki_page}
            </div>
          </button>
        );
      })}
    </div>
  );
}